### List teams
GET http://localhost:3000/teams

### List team
GET http://localhost:3000/teams/1

### Create team
POST http://localhost:3000/teams
Content-Type: application/json

{
   "name_team": "Corintians",
   "group_team": "A",
   "defense": 61,
   "attack": 69,
   "points": 3
}

### Update team
PATCH  http://localhost:3000/teams/1

### Delete team
DELETE http://localhost:3000/teams/2