### List teams
GET http://localhost:3000/teams

### List team
GET http://localhost:3000/teams/1

### Create team
POST http://localhost:3000/teams
Content-Type: application/json

{
   "nome": "Corintians",
   "grupo": "A",
   "def": 61,
   "ata": 69,
   "pontos": 0
}

### Update team
PATCH  http://localhost:3000/teams/1

### Delete team
DELETE http://localhost:3000/teams/1